<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-581550-1694581992/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)

# Display the array
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
zeros_array = np.zeros(10)

# Display the array
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 zeros
zeros_array = [0.0] * 10

# Display the array two times
for _ in range(2):
    print("array","(",zeros_array,")")

array ( [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] )
array ( [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] )


In [ ]:
# Create an array of 10 ones
ones_array = np.ones(10)

# Display the array
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# Create an array of 10 ones
ones_array = np.ones(10)

# Display the array
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Define an array filled with 1s
ones_array = np.ones(10)

# Display the array three times
for _ in range(3):
    print("array","(",ones_array,")")

array ( [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] )
array ( [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] )
array ( [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] )


In [ ]:
# Create an array of 10 fives
my_array = [5.]*10

# Print the array
print(my_array)

[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]


In [ ]:
# Create an array of 10 fives
my_array = [5.0] * 10

# Print the array
print("array","(",my_array,")")

array ( [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0] )


In [ ]:
# Create an array of 10 fives
my_array = [5.0] * 10

# Display the array four times
for _ in range(4):
    print("array","(",my_array,")")

array ( [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0] )
array ( [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0] )
array ( [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0] )
array ( [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0] )


In [ ]:
# Create an array of integers from 10 to 50
my_array = [i for i in range(10, 51)]

# Print the array
print(my_array)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [ ]:
my_array = np.arange(10, 51)

# Print the array
print("array(",my_array,")")

array( [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] )
